SKILL_SYNONYMS = {
    "ab testing": ["a/b testing", "ab testing", "experimentation"],
    "agile": ["agile", "scrum", "kanban"],
    "airflow": ["airflow", "apache airflow"],
    "algorithms": ["algorithm", "algorithms"],
    "analytics": ["analytics", "data analytics", "business analytics"],
    "android": ["android"],
    "api development": ["api development", "backend api", "backend api development"],
    "aws": ["aws", "amazon web services"],
    "azure": ["azure", "microsoft azure"],
    "big data": ["big data", "large-scale data"],
    "c": [" c ", "c programming"],
    "c++": ["c++", "cpp"],
    "ci/cd": ["ci/cd", "continuous integration", "continuous deployment"],
    "cloud computing": ["cloud", "cloud computing", "cloud platform"],
    "computer networks": ["computer network", "computer networks", "networking"],
    "containerization": ["container", "containers", "containerization"],
    "css": ["css"],
    "cybersecurity": ["cyber security", "cybersecurity", "security engineering"],
    "data engineering": ["data engineering", "data engineer", "data pipelines", "data pipeline"],
    "data visualization": ["data visualization", "dashboard", "dashboards", "visualization"],
    "data structures": ["data structure", "data structures"],
    "databases": ["database", "databases"],
    "distributed systems": ["distributed system", "distributed systems"],
    "docker": ["docker"],
    "excel": ["excel", "spreadsheets"],
    "fastapi": ["fastapi"],
    "flask": ["flask"],
    "git": ["git", "github", "gitlab"],
    "gcp": ["gcp", "google cloud", "google cloud platform"],
    "go": ["go", "golang"],
    "html": ["html"],
    "java": ["java"],
    "javascript": ["javascript", "js"],
    "kafka": ["kafka", "apache kafka"],
    "kotlin": ["kotlin"],
    "kubernetes": ["kubernetes", "k8s"],
    "langchain": ["langchain"],
    "linux": ["linux", "unix"],
    "machine learning": ["machine learning", "ml", "ai/ml"],
    "microservices": ["microservice", "microservices"],
    "mongodb": ["mongodb", "mongo"],
    "neo4j": ["neo4j"],
    "nlp": ["nlp", "natural language processing"],
    "node.js": ["node.js", "nodejs", "node"],
    "operating systems": ["operating system", "operating systems", "os internals"],
    "pandas": ["pandas"],
    "postgresql": ["postgresql", "postgres"],
    "python": ["python"],
    "pytorch": ["pytorch"],
    "react": ["react", "react.js", "reactjs"],
    "rest api": ["rest api", "restful api", "rest"],
    "scikit-learn": ["scikit-learn", "sklearn"],
    "spark": ["spark", "apache spark", "pyspark"],
    "sql": ["sql"],
    "statistics": ["statistics", "statistical analysis", "statistical modelling", "statistical modeling"],
    "swift": ["swift"],
    "tableau": ["tableau"],
    "tensorflow": ["tensorflow"],
    "terraform": ["terraform"],
    "threat detection": ["threat detection", "security detection"],
    "typescript": ["typescript", "ts"],
    "ui/ux": ["ui/ux", "user experience", "user interface"],
}
